export const GEM_POINT_TRANSACTION_TYPE = {
  VERIFIED_VISIT: "GEM_VERIFIED_VISIT",
  VERIFIED_REVIEW: "GEM_VERIFIED_REVIEW",
  VERIFIED_REVIEW_WITH_IMAGE: "GEM_VERIFIED_REVIEW_WITH_IMAGE",
} as const;
